name: finalproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  get: ^4.7.3
  fl_chart: 0.69.0
  intl: ^0.20.2
  hive_flutter: ^1.1.0
  supabase: ^2.10.0
  supabase_flutter: ^2.6.0
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.15.0
  dartx: ^1.2.0
  get_storage: ^2.1.1
  path_provider: ^2.1.2
  
  # Auth & Social
  google_sign_in: ^6.2.1
  
  # Clean Architecture Dependencies
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  get_it: ^8.0.3
  
  # UI/UX
  google_fonts: ^6.1.0
  lottie: ^3.1.3
  animate_do: ^3.3.4
  percent_indicator: ^4.2.3
  glassmorphism: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.7.0
  
  # Network
  connectivity_plus: ^5.0.2
  dio: ^5.7.0
  http: ^1.3.0
  url_launcher: ^6.2.4
  
  # Scan & Utils
  mobile_scanner: ^6.0.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  hive: ^2.2.3
  uuid: ^4.5.1
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo_elegant.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo_elegant.png"
    background_color: "#121212"
    theme_color: "#0D47A1"
  windows:
    generate: true
    image_path: "assets/images/app_logo_elegant.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo_elegant.png"

flutter_native_splash:
  color: "#121212"
  image: assets/images/app_logo_elegant.png
  branding: assets/images/app_logo_elegant.png
  color_dark: "#121212"
  image_dark: assets/images/app_logo_elegant.png
  branding_dark: assets/images/app_logo_elegant.png

  android_12:
    image: assets/images/app_logo_elegant.png
    icon_background_color: "#121212"
    image_dark: assets/images/app_logo_elegant.png
    icon_background_color_dark: "#121212"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
